export const InjectionKey = {
    USER_CRUD_VALIDATOR: "USER_CRUD_VALIDATOR",
    USER_SERVICE: "USER_SERVICE",
    USER_REPOSITORY: "USER_REPOSITORY",
    ERROR_MIDDLEWARE: "ERROR_MIDDLEWARE",
    FILE_SAVE_SERVICE: "FILE_SAVE_SERVICE",
    TOKEN_GENERATOR_SERVICE: "TOKEN_GENERATOR_SERVICE"
}